version: '3'
services:
  bot:
    container_name: 'HamsterKombatBot'
    image: ghcr.io/shamhi/hamsterkombatbot:latest
    stop_signal: SIGINT
    restart: unless-stopped
    command: 
      - python3
      - main.py
      - -a
      - '2'
    volumes:
      - ./sessions:/app/sessions
      - ./proxies.txt:/app/proxies.txt
    env_file:
      - .env
