name: Build, Test and Push Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/shamhi/hamsterkombatbot

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          logout: false

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
#          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Test Docker image
#        run: |
#          echo "API_ID=API_ID" > .env
#          echo "API_HASH=API_HASH" >> .env
#          sed -i "s|image: ${IMAGE_NAME}:latest|image: ${IMAGE_NAME}:test|" docker-compose.yml
#          export ARGUMENT=1
#          docker compose up -d
#          sleep 10
#          docker compose ps

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Scan image for vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ${{ env.IMAGE_NAME }}:latest
          fail-build: true